### ISSUE TITLE
processDefaultFileSet property is not working

### ISSUE THREAD

**Issue by ravalli** [wildfly/jandex-maven-plugin#16] opened 2020-03-12 15:16 UTC
It doesn't matter the value defined in the property, the default file set is always processed. 

The possible reason of this behavior could be the snippet code below: 

```java
    /**
     * If true, construct an implied file-set using the target/classes directory, and process the classes there.
     *
     * @parameter default-value="true"
     */
    private final boolean processDefaultFileSet = true;
```

**Comment by t1** [comment] 2020-06-23 04:47
I have the use-case that I only want to index the test-classes, but a second index `target/classes/META-INF/jandex.idx` is generated nonetheless.

**Comment by t1** [comment] 2020-06-23 05:28
I just found out that this seems to be fixed in 1.0.8. See [here](https://github.com/wildfly/jandex-maven-plugin/commit/f3398714799bfabd0b09da725a8b30269b0eb61e#diff-893d48326bad155611585f46cfd29d9bL91)

**Comment by Ladicek** [comment] 2021-08-31 15:16
I can confirm this is indeed fixed.

**Comment by Ladicek** [comment] 2021-09-01 12:43
I have write permissions now :-), so closing.

**Closed by Ladicek** 2021-09-01 12:43 UTC
